import { Header } from "~/components/Header";
import { Footer } from "~/components/Footer";

export const metadata = {
  title: "Terms & Conditions | VoyageGH",
};

export default function TermsPage() {
  return (
    <div className="flex flex-col min-h-screen">
      <Header />
      <main className="wrapper py-10 flex-1">
        <div className="max-w-3xl mx-auto flex flex-col gap-8">
          <h1 className="text-3xl font-bold text-dark-100">Terms & Conditions</h1>
          <div className="prose text-gray-100 flex flex-col gap-4">
            <p>Welcome to VoyageGH. By using our platform, you agree to the following terms and conditions.</p>
            <h2 className="text-xl font-semibold text-dark-100">1. Acceptance of Terms</h2>
            <p>By accessing and using VoyageGH, you accept and agree to be bound by these Terms and Conditions. If you do not agree, please do not use our service.</p>
            <h2 className="text-xl font-semibold text-dark-100">2. Service Description</h2>
            <p>VoyageGH is an AI-powered travel agency platform that generates personalized travel itineraries for destinations in Ghana. We provide trip planning, booking, and review services.</p>
            <h2 className="text-xl font-semibold text-dark-100">3. User Accounts</h2>
            <p>You are responsible for maintaining the confidentiality of your account credentials. You agree to provide accurate and complete information when creating an account.</p>
            <h2 className="text-xl font-semibold text-dark-100">4. Bookings and Payments</h2>
            <p>All bookings are subject to availability. Prices are displayed in Ghana Cedis (GH₵) and may change without notice. Payment processing is handled by our secure payment partners.</p>
            <h2 className="text-xl font-semibold text-dark-100">5. Cancellation Policy</h2>
            <p>You may cancel a booking up to 48 hours before the trip start date for a full refund. Cancellations within 48 hours may be subject to a cancellation fee.</p>
            <h2 className="text-xl font-semibold text-dark-100">6. AI-Generated Content</h2>
            <p>Travel itineraries are generated by artificial intelligence and should be used as recommendations. Actual experiences may vary. We recommend confirming details with local providers.</p>
            <h2 className="text-xl font-semibold text-dark-100">7. User Reviews</h2>
            <p>By submitting a review, you grant VoyageGH a non-exclusive license to use, modify, and display your review content. Reviews must be truthful and not violate any laws.</p>
            <h2 className="text-xl font-semibold text-dark-100">8. Limitation of Liability</h2>
            <p>VoyageGH is not liable for any damages arising from the use of our service, including but not limited to trip disruptions, inaccurate AI recommendations, or third-party service failures.</p>
            <h2 className="text-xl font-semibold text-dark-100">9. Changes to Terms</h2>
            <p>We reserve the right to modify these terms at any time. Continued use of the service after changes constitutes acceptance of the new terms.</p>
            <p className="text-sm text-gray-100 mt-4">Last updated: July 2025</p>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
